name: 'AWS - Dev - Terraform Test'
on:      
  push:
    # branches: [ "feature/*" ]
    branches-ignore:
    - feature/helm-pipeline
    - main
  pull_request:
    # branches: [ "feature/*" ]
    branches-ignore:
    - feature/helm-pipeline
    - main

permissions:
  contents: read
  id-token: write
  checks: write
  pull-requests: write
  issues: write

defaults:
  run:
    shell: bash

jobs:
  aws-terraform-test:
    name: 'Plan and Test Terraform - aws - staging'
    uses: ./.github/workflows/terraform.yaml
    with:
      environment: staging
      aws_region: eu-west-2