name: 'Kubernetes - Dev - Helm Test'
on:      
  push:
    # branches: [ "feature/*" ]
    branches-ignore:
    - feature/helm-pipeline
    - main
  pull_request:
    # branches: [ "feature/*" ]
    branches-ignore:
    - feature/helm-pipeline
    - main

permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  aws-terraform-test:
    name: 'Lint and Template Helm - kubernetes - dev'
    uses: ./.github/workflows/helm.yaml
    with:
      environment: dev